version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

# Entry for the CLI Dockerfile
  - package-ecosystem: "docker"
    directory: "/cli"
    schedule:
      interval: "weekly"

  # Entry for the FPM Dockerfile
  - package-ecosystem: "docker"
    directory: "/fpm"
    schedule:
      interval: "weekly"

  # Entry for the Nginx Dockerfile
  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "weekly"
