name: Docker build
on: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 */14 * *'
  workflow_dispatch:

jobs:
  build-cli:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - version: "8.3"
            pkg: "83"
          - version: "8.4"
            pkg: "84"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v7
      -
        name: Modify Dockerfile version
        run: |
          sed -i "s/php83/php${{ matrix.pkg }}/g;s/php84-json//g" cli/Dockerfile
          # If we are building 8.4, upgrade Alpine 3.20 to 3.21
          if [ "${{ matrix.version }}" = "8.4" ]; then
            sed -i "s/alpine:3.20/alpine:3.23/g" cli/Dockerfile
          fi
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: cli/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/sentratek-id/alpine-php/cli:${{ matrix.version }}

  build-fpm:
    needs: build-cli
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - version: "8.3"
            pkg: "83"
          - version: "8.4"
            pkg: "84"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v7
      -
        name: Modify Dockerfile version
        run: |
          sed -i "s/php83/php${{ matrix.pkg }}/g;s/php84-json//g" fpm/Dockerfile
          # If we are building 8.4, upgrade Alpine 3.20 to 3.21
          if [ "${{ matrix.version }}" = "8.4" ]; then
            sed -i "s/alpine:3.20/alpine:3.23/g" fpm/Dockerfile
          fi
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: fpm/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/sentratek-id/alpine-php/fpm:${{ matrix.version }}

  build-octane:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - version: "8.3"
            pkg: "83"
          - version: "8.4"
            pkg: "84"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v7
      -
        name: Modify Dockerfile version
        run: |
          sed -i "s/php83/php${{ matrix.pkg }}/g;s/php84-json//g" octane/Dockerfile
          # PHP 8.4 specific adjustments (Upgrade Alpine, drop PEAR, remove PECL command)
          if [ "${{ matrix.version }}" = "8.4" ]; then
            sed -i "s/alpine:3.20/alpine:3.23/g" octane/Dockerfile
          fi
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: octane/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/sentratek-id/alpine-php/octane:${{ matrix.version }}

  build-nginx:
    needs: build-fpm
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - version: "8.3"
            pkg: "83"
          - version: "8.4"
            pkg: "84"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v7
      -
        name: Modify Dockerfile version
        run: |
          sed -i "s/php83/php${{ matrix.pkg }}/g;s/php84-json//g" nginx/Dockerfile
          # If we are building 8.4, upgrade Alpine 3.20 to 3.21
          if [ "${{ matrix.version }}" = "8.4" ]; then
            sed -i "s/alpine:3.20/alpine:3.23/g" nginx/Dockerfile
          fi
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: nginx/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/sentratek-id/alpine-php/nginx:${{ matrix.version }}
